### ISSUE TITLE
A friendly code review of your Simon game

### ISSUE THREAD

**Issue by pserwylo** [IT-Jeroen/Udemy-FullStack#2]
Wow, nice work. Really love the visual style, and the old-school bitmap font. Looks very schmick.

The code is also starting to show some really great usage of functions. It reads really well, and makes a lot of sense.

Could I challenge you to make an improvement? Given you have [all the info you need to query the DOM and find out how many / what tiles exist](https://github.com/IT-Jeroen/Photo_Site/blob/39ecaa39db017153f914a3bb2da52fe9bade1ca2/game.js#L80), can you change the game so that it supports any number of tiles, by just adding an appropriate `<div>` to the HTML? I would be happy to provide some pointers, but think that at the rate you're going, you'd probably be able to figure it out soon anyway. Just reach out if you want any suggestions.

The only constructive feedback I have regarding the layout of your functions is with the [`buttonSequence(...)`](https://github.com/IT-Jeroen/Photo_Site/blob/39ecaa39db017153f914a3bb2da52fe9bade1ca2/game.js#L6) function. When you see a function with an argument, which does one thing if present, and another if not, it is typically considered a "code-smell". Instead of having this one function, I'd probably have something like this:

```
function onButtonSelected(colour) {
  userClickedButton.push(colour)
  highlightButton(colour)
}

function generateNextSequence() {
  colour = random colour
  gamePattern.push(colour)
  highlightButton(colour)
}

function highlightButton(colour) {
  play sound
  fade in and out
  add shadow
}
```

For a more detailed argument, check out this article from a well-respected software writer Martin Fowler: https://www.martinfowler.com/bliki/FlagArgument.html. 

All in all, very cool to watch this stuff come along, well done.

**Comment by IT-Jeroen** [comment]
I have updated the code to reflect your feedback.
I have also updated the game so that the user can choose a number of tiles which will then be auto generated.

Looking forward to your feedback.

**Comment by IT-Jeroen** [comment]
Received no more feedback on latest changes
